// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycfzshkqeztjyyvsyycv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljZnpzaGtxZXp0anl5dnN5eWN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzOTIzMTAsImV4cCI6MjA1Njk2ODMxMH0.xKnEfrxkbLa5qEo3lolDvO9lFgcAeigoot37gYor1Oc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
